# Generated by Django 5.1.2 on 2024-10-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
