# Generated by Django 5.1.2 on 2024-11-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0008_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
