# Generated by Django 5.1.2 on 2024-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0012_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
