# Generated by Django 5.1.2 on 2024-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0013_blogpost_remove_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
    ]
