# Generated by Django 5.1.2 on 2024-11-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0015_blogpost_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'managed': True},
        ),
    ]
