# Generated by Django 5.1.2 on 2024-11-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0016_alter_blog_options_alter_blogpost_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='Blog',
        ),
    ]
