# Generated by Django 5.1.2 on 2024-11-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0017_rename_title_blog_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Blog',
            new_name='title',
        ),
    ]
