# Generated by Django 5.1.2 on 2024-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0018_rename_blog_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
